services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: in-home-care-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
volumes:
  prometheus-data:

networks:
  in-home-care-network:
    external: true
